version: "3.9"

services:
  traefik:
    image: traefik:latest
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - .env.services
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yml:/traefik.yml:ro
      - ./traefik/acme.json:/acme.json
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik-secure.tls=true"
      - "traefik.http.routers.traefik-secure.tls.certresolver=cloudflare"
      - "traefik.http.routers.traefik-secure.tls.domains[0].sans=*.epicfreegames.net"
    networks:
      - efg

  uptime-kuma:
    image: louislam/uptime-kuma
    restart: always
    volumes:
      - ./DATA/uptime-kuma:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.efg-uptime-kuma.entrypoints=https"
      - "traefik.http.routers.efg-uptime-kuma.tls=true"
      - "traefik.http.routers.efg-uptime-kuma.service=efg-uptime-kuma"
      - "traefik.http.routers.efg-uptime-kuma.rule=Host(`status.epicfreegames.net`)"
      - "traefik.http.services.efg-uptime-kuma.loadbalancer.server.port=3001"
      - "traefik.docker.network=efg"
    networks:
      - efg

  postgres:
    image: postgres:14.5
    restart: always
    volumes:
      - ./DATA/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - efg

  plausible_events_db:
    image: yandex/clickhouse-server:21.3.2.5
    restart: always
    volumes:
      - ./DATA/plausible_events_db:/var/lib/clickhouse
      - ./clickhouse/clickhouse-config.xml:/etc/clickhouse-server/config.d/logging.xml:ro
      - ./clickhouse/clickhouse-user-config.xml:/etc/clickhouse-server/users.d/logging.xml:ro
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - efg

  plausible:
    image: plausible/analytics:latest
    restart: always
    command: sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh db init-admin && /entrypoint.sh run"
    depends_on:
      - postgres
      - plausible_events_db
    environment:
      DISABLE_REGISTRATION: true
      SMTP_HOST_SSL_ENABLED: true
      BASE_URL: https://a7s.epicfreegames.net
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/plausible
      CLICKHOUSE_DATABASE_URL: http://plausible_events_db:8123/plausible_events_db
    env_file:
      - .env.services
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.efg-plausible.entrypoints=https"
      - "traefik.http.routers.efg-plausible.tls=true"
      - "traefik.http.routers.efg-plausible.service=efg-plausible"
      - "traefik.http.routers.efg-plausible.rule=Host(`a7s.epicfreegames.net`)"
      - "traefik.http.services.efg-plausible.loadbalancer.server.port=8000"
      - "traefik.docker.network=efg"
    networks:
      - efg

networks:
  efg:
    external: true
