FROM node:16-alpine AS base

WORKDIR /app

FROM base as builder

COPY ./*.json ./
COPY ./yarn.lock ./
COPY ./*d.ts ./
COPY ./*.js ./

RUN yarn

COPY ./src ./src
COPY ./public ./public

ENV NODE_ENV development
ENV NEXT_TELEMETRY_DISABLED 1

CMD yarn dev