version: "3.9"

services:
  efg-db:
    image: mongo:4.4.7
    expose:
      - 27017
    ports:
      - "50001:27017"
    volumes:
      - ./DATA/database:/data/db
      - ./DATA/conf:/data/configdb
    env_file:
      - .env.mongo
    restart: unless-stopped
    networks:
      - efg

  efg-endpoint:
    depends_on:
      - efg-db
    build: .
    image: efg-endpoint
    entrypoint:
      ["yarn", "dev", "--scope=interactions-endpoint", "--include-dependencies", "--no-deps"]
    deploy:
      replicas: 2
    restart: unless-stopped
    networks:
      - efg

  efg-sender:
    depends_on:
      - efg-db
      - efg-endpoint
    build: .
    image: efg-sender
    entrypoint: ["yarn", "dev", "--scope=sender", "--include-dependencies", "--no-deps"]
    restart: unless-stopped
    networks:
      - efg

  efg-client:
    depends_on:
      - efg-db
    build: .
    image: efg-client
    entrypoint: ["yarn", "dev", "--scope=discordjs-client", "--include-dependencies", "--no-deps"]
    restart: unless-stopped
    networks:
      - efg

  efg-scrapers:
    depends_on:
      - efg-db
    build: .
    image: efg-scrapers
    entrypoint: ["yarn", "dev", "--scope=scrapers", "--include-dependencies", "--no-deps"]
    restart: unless-stopped
    networks:
      - efg

  efg-loadbalancer:
    depends_on:
      - efg-db
      - efg-endpoint
      - efg-sender
    image: nginx
    ports:
      - "50000:5000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: unless-stopped
    networks:
      - efg

networks:
  efg:
