version: "3.9"

services:
    db:
        image: mongo
        restart: always
        ports:
            - 27017:27017
        volumes:
            - db_data:/data/db
            - db_config:/data/configdb

    backend:
        build: ./backend
        restart: always
        ports:
            - 10000:5000
        environment:
            - DC_API_BASE=${DC_API_BASE}
            - DC_PUB_KEY=${DC_PUB_KEY}
            - DC_CLIENT_ID=${DC_CLIENT_ID}
            - DC_TOKEN=${DC_TOKEN}
            - ENV=${ENV}
            - MONGO_URL=mongodb://db:27017
            - PRETTY_LOG=1
            - LOG=debug
            - PORT=5000

    proxy:
        image: twilight-rs--http-proxy
        restart: always
        environment:
            - DISCORD_TOKEN=${DC_TOKEN}

volumes:
    db_data:
    db_config:
