version: "3.9"

services:
  endpoint:
    depends_on:
      - db
    build: .
    image: endpoint
    entrypoint:
      ["yarn", "dev", "--scope=interactions-endpoint", "--include-dependencies", "--no-deps"]
    deploy:
      replicas: 2
    restart: unless-stopped

  sender:
    depends_on:
      - db
      - endpoint
    build: .
    image: sender
    entrypoint: ["yarn", "dev", "--scope=sender", "--include-dependencies", "--no-deps"]
    restart: unless-stopped

  client:
    depends_on:
      - db
    build: .
    image: client
    entrypoint: ["yarn", "dev", "--scope=discordjs-client", "--include-dependencies", "--no-deps"]
    restart: unless-stopped

  scrapers:
    depends_on:
      - db
    build: .
    image: scrapers
    entrypoint: ["yarn", "dev", "--scope=scrapers", "--include-dependencies", "--no-deps"]
    restart: unless-stopped