services:
    backend:
        image: veetik/efg-backend
        env_file:
            - .env.prod.backend
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.efg-backend.entrypoints=https"
            - "traefik.http.routers.efg-backend.tls=true"
            - "traefik.http.routers.efg-backend.service=efg-backend"
            - "traefik.http.routers.efg-backend.rule=Host(`redirect.epicfreegames.net`) || Host(`api.epicfreegames.net`)"
            - "traefik.http.services.efg-backend.loadbalancer.server.port=8000"
            - "traefik.docker.network=efg":
        networks:
            - efg

    proxy:
        image: veetik/efg-proxy
        env_file:
            - .env.prod.proxy
        networks:
            - efg

networks:
    efg:
        external: true
