use std::collections::HashMap;

use i18n::{translator::Translator, types::Language};
use twilight_model::{
    application::command::{Command, CommandType},
    guild::Permissions,
    id::Id,
};

pub fn get_slash_commands() -> Vec<Command> {
    let translator = Translator::new();
    let language = Language::default();

    Vec::from([
        Command {
            name: "free".to_string(),
            description: translator.translate("cmd_desc_free", &language, None),
            default_member_permissions: None,
            dm_permission: Some(true),
            kind: CommandType::ChatInput,
            version: Id::new(1u64),
            description_localizations: None,
            name_localizations: None,
            nsfw: None,
            options: Vec::new(),
            guild_id: None,
            id: None,
            application_id: None,
        },
        Command {
            name: "up".to_string(),
            description: translator.translate("cmd_desc_up", &language, None),
            default_member_permissions: None,
            dm_permission: Some(true),
            kind: CommandType::ChatInput,
            version: Id::new(1u64),
            description_localizations: None,
            name_localizations: None,
            nsfw: None,
            options: Vec::new(),
            guild_id: None,
            id: None,
            application_id: None,
        },
        Command {
            name: "vote".to_string(),
            description: translator.translate("cmd_desc_vote", &language, None),
            default_member_permissions: None,
            dm_permission: Some(true),
            kind: CommandType::ChatInput,
            version: Id::new(1u64),
            description_localizations: None,
            name_localizations: None,
            nsfw: None,
            options: Vec::new(),
            guild_id: None,
            id: None,
            application_id: None,
        },
        Command {
            name: "help".to_string(),
            description: translator.translate("cmd_desc_help", &language, None),
            default_member_permissions: None,
            dm_permission: Some(true),
            kind: CommandType::ChatInput,
            version: Id::new(1u64),
            description_localizations: None,
            name_localizations: None,
            nsfw: None,
            options: Vec::new(),
            guild_id: None,
            id: None,
            application_id: None,
        },
        Command {
            name: "invite".to_string(),
            description: translator.translate("cmd_desc_invite", &language, None),
            default_member_permissions: None,
            dm_permission: Some(true),
            kind: CommandType::ChatInput,
            version: Id::new(1u64),
            description_localizations: None,
            name_localizations: None,
            nsfw: None,
            options: Vec::new(),
            guild_id: None,
            id: None,
            application_id: None,
        },
        Command {
            name: "settings".to_string(),
            description: translator.translate("cmd_desc_settings", &language, None),
            default_member_permissions: Some(Permissions::MANAGE_GUILD),
            dm_permission: Some(false),
            kind: CommandType::ChatInput,
            version: Id::new(1u64),
            description_localizations: None,
            name_localizations: None,
            nsfw: None,
            options: Vec::new(),
            guild_id: None,
            id: None,
            application_id: None,
        },
        Command {
            name: "test".to_string(),
            description: translator.translate("cmd_desc_test", &language, None),
            default_member_permissions: Some(Permissions::MANAGE_GUILD),
            dm_permission: Some(false),
            kind: CommandType::ChatInput,
            version: Id::new(1u64),
            description_localizations: None,
            name_localizations: None,
            nsfw: None,
            options: Vec::new(),
            guild_id: None,
            id: None,
            application_id: None,
        },
        Command {
            name: "debug".to_string(),
            description: translator.translate("cmd_desc_debug", &language, None),
            default_member_permissions: Some(Permissions::MANAGE_GUILD),
            dm_permission: Some(false),
            kind: CommandType::ChatInput,
            version: Id::new(1u64),
            description_localizations: None,
            name_localizations: None,
            nsfw: None,
            options: Vec::new(),
            guild_id: None,
            id: None,
            application_id: None,
        },
    ])
}
