//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "session")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    pub created_at: DateTime,
    pub expires_at: DateTime,
    #[sea_orm(column_type = "Text")]
    pub ip: String,
    #[sea_orm(column_type = "Text")]
    pub user_agent: String,
    #[sea_orm(column_type = "Text")]
    pub user_id: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::api_user::Entity",
        from = "Column::UserId",
        to = "super::api_user::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    ApiUser,
}

impl Related<super::api_user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ApiUser.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
