version: "3.9"

services:
  uptime-kuma:
    image: louislam/uptime-kuma
    restart: always
    volumes:
      - ./DATA/uptime-kuma:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.efg-uptime-kuma.entrypoints=https"
      - "traefik.http.routers.efg-uptime-kuma.tls=true"
      - "traefik.http.routers.efg-uptime-kuma.service=efg-uptime-kuma"
      - "traefik.http.routers.efg-uptime-kuma.rule=Host(`status.epicfreegames.net`)"
      - "traefik.http.services.efg-uptime-kuma.loadbalancer.server.port=3001"
      - "traefik.docker.network=proxy"
    networks:
      - proxy

  plausible_db:
    image: postgres:12
    restart: always
    volumes:
      - ./DATA/plausible_db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: plausible
    networks:
      - proxy

  plausible_events_db:
    image: yandex/clickhouse-server:21.3.2.5
    restart: always
    volumes:
      - ./DATA/plausible_events_db:/var/lib/clickhouse
      - ./clickhouse/clickhouse-config.xml:/etc/clickhouse-server/config.d/logging.xml:ro
      - ./clickhouse/clickhouse-user-config.xml:/etc/clickhouse-server/users.d/logging.xml:ro
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - proxy

  plausible:
    image: plausible/analytics:latest
    restart: always
    command: sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh db init-admin && /entrypoint.sh run"
    depends_on:
      - plausible_db
      - plausible_events_db
    environment:
      DISABLE_REGISTRATION: true
      SMTP_HOST_SSL_ENABLED: true
      BASE_URL: https://a7s.epicfreegames.net
      DATABASE_URL: postgres://postgres:postgres@plausible_db:5432/plausible
      CLICKHOUSE_DATABASE_URL: http://plausible_events_db:8123/plausible_events_db
      ADMIN_USER_EMAIL: ${PLAUSIBLE_ADMIN_USER_EMAIL}
      ADMIN_USER_NAME: ${PLAUSIBLE_ADMIN_USER_NAME}
      ADMIN_USER_PWD: ${PLAUSIBLE_ADMIN_USER_PWD}
      SECRET_KEY_BASE: ${PLAUSIBLE_SECRET_KEY_BASE}
      MAILER_EMAIL: ${PLAUSIBLE_MAILER_EMAIL}
      SMTP_HOST_ADDR: ${PLAUSIBLE_SMTP_HOST_ADDR}
      SMTP_HOST_PORT: ${PLAUSIBLE_SMTP_HOST_PORT}
      SMTP_USER_NAME: ${PLAUSIBLE_SMTP_USER_NAME}
      SMTP_USER_PWD: ${PLAUSIBLE_SMTP_USER_PWD}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.efg-plausible.entrypoints=https"
      - "traefik.http.routers.efg-plausible.tls=true"
      - "traefik.http.routers.efg-plausible.service=efg-plausible"
      - "traefik.http.routers.efg-plausible.rule=Host(`a7s.epicfreegames.net`)"
      - "traefik.http.services.efg-plausible.loadbalancer.server.port=8000"
      - "traefik.docker.network=proxy"
    networks:
      - proxy

networks:
  proxy:
    external: true

  # weblate-postgres:
  #   image: postgres:14-alpine
  #   volumes:
  #     - ./DATA/weblate-postgres:/var/lib/postgresql/data
  #   environment:
  #     POSTGRES_PASSWORD: weblate
  #     POSTGRES_USER: weblate
  #     POSTGRES_DATABASE: weblate
  #   restart: always
  #   networks:
  #     - proxy

  # weblate-redis:
  #   image: redis:6-alpine
  #   restart: always
  #   command: [redis-server, --save, "60", "1"]
  #   volumes:
  #     - ./DATA/weblate-redis:/data
  #   networks:
  #     - proxy

  # weblate:
  #   depends_on:
  #     - weblate-postgres
  #     - weblate-redis
  #   image: weblate/weblate
  #   tmpfs:
  #     - /app/cache
  #   volumes:
  #     - weblate:/app/data
  #   environment:
  #     POSTGRES_PASSWORD: weblate
  #     POSTGRES_USER: weblate
  #     POSTGRES_DATABASE: weblate
  #     POSTGRES_HOST: weblate-postgres
  #     POSTGRES_PORT: 5432
  #     REDIS_HOST: weblate-redis
  #     REDIS_PORT: 6379
  #     WEBLATE_OFFLOAD_INDEXING: 1
  #     WEBLATE_REQUIRE_LOGIN: 1
  #     WEBLATE_DEBUG: 1
  #     WEBLATE_LOGLEVEL: DEBUG
  #     WEBLATE_ALLOWED_HOSTS: "*"
  #     WEBLATE_REGISTRATION_OPEN: 1
  #     WEBLATE_SITE_DOMAIN: t.epicfreegames.net
  #     WEBLATE_EMAIL_HOST: ${WEBLATE_EMAIL_HOST}
  #     WEBLATE_EMAIL_PORT: ${WEBLATE_EMAIL_PORT}
  #     WEBLATE_EMAIL_HOST_USER: ${WEBLATE_EMAIL_HOST_USER}
  #     WEBLATE_EMAIL_HOST_PASSWORD: ${WEBLATE_EMAIL_HOST_PASSWORD}
  #     WEBLATE_ADMIN_EMAIL: ${WEBLATE_ADMIN_EMAIL}
  #     WEBLATE_ADMIN_PASSWORD: ${WEBLATE_ADMIN_PASSWORD}
  #     WEBLATE_SERVER_EMAIL: ${WEBLATE_SERVER_EMAIL}
  #     WEBLATE_DEFAULT_FROM_EMAIL: ${WEBLATE_DEFAULT_FROM_EMAIL}
  #   restart: always
  #   networks:
  #     - proxy
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.efg-t.entrypoints=https"
  #     - "traefik.http.routers.efg-t.tls=true"
  #     - "traefik.http.routers.efg-t.service=efg-t"
  #     - "traefik.http.routers.efg-t.rule=Host(`t.epicfreegames.net`)"
  #     - "traefik.http.services.efg-t.loadbalancer.server.port=8080"
  #     - "traefik.docker.network=proxy"
# volumes:
#   weblate:
