use i18n::{translator::Translator, types::Language};
use twilight_model::{
    application::command::{Command, CommandOption, CommandOptionType, CommandType},
    channel::ChannelType,
    guild::Permissions,
    id::Id,
};

pub fn get_slash_commands() -> Vec<Command> {
    let translator = Translator::new();
    let language = Language::default();

    Vec::from([
        Command {
            name: "free".to_string(),
            description: translator.translate("cmd_desc_free", &language, None),
            default_member_permissions: None,
            dm_permission: Some(true),
            kind: CommandType::ChatInput,
            version: Id::new(1u64),
            description_localizations: None,
            name_localizations: None,
            nsfw: None,
            options: Vec::new(),
            guild_id: None,
            id: None,
            application_id: None,
        },
        Command {
            name: "up".to_string(),
            description: translator.translate("cmd_desc_up", &language, None),
            default_member_permissions: None,
            dm_permission: Some(true),
            kind: CommandType::ChatInput,
            version: Id::new(1u64),
            description_localizations: None,
            name_localizations: None,
            nsfw: None,
            options: Vec::new(),
            guild_id: None,
            id: None,
            application_id: None,
        },
        Command {
            name: "vote".to_string(),
            description: translator.translate("cmd_desc_vote", &language, None),
            default_member_permissions: None,
            dm_permission: Some(true),
            kind: CommandType::ChatInput,
            version: Id::new(1u64),
            description_localizations: None,
            name_localizations: None,
            nsfw: None,
            options: Vec::new(),
            guild_id: None,
            id: None,
            application_id: None,
        },
        Command {
            name: "help".to_string(),
            description: translator.translate("cmd_desc_help", &language, None),
            default_member_permissions: None,
            dm_permission: Some(true),
            kind: CommandType::ChatInput,
            version: Id::new(1u64),
            description_localizations: None,
            name_localizations: None,
            nsfw: None,
            options: Vec::new(),
            guild_id: None,
            id: None,
            application_id: None,
        },
        Command {
            name: "invite".to_string(),
            description: translator.translate("cmd_desc_invite", &language, None),
            default_member_permissions: None,
            dm_permission: Some(true),
            kind: CommandType::ChatInput,
            version: Id::new(1u64),
            description_localizations: None,
            name_localizations: None,
            nsfw: None,
            options: Vec::new(),
            guild_id: None,
            id: None,
            application_id: None,
        },
        Command {
            name: "settings".to_string(),
            description: translator.translate("cmd_desc_settings", &language, None),
            default_member_permissions: Some(Permissions::MANAGE_GUILD),
            dm_permission: Some(false),
            kind: CommandType::ChatInput,
            version: Id::new(1u64),
            description_localizations: None,
            name_localizations: None,
            nsfw: None,
            options: Vec::new(),
            guild_id: None,
            id: None,
            application_id: None,
        },
        Command {
            name: "set".to_string(),
            description: translator.translate("cmd_desc_settings", &language, None),
            default_member_permissions: Some(Permissions::MANAGE_GUILD),
            dm_permission: Some(false),
            kind: CommandType::ChatInput,
            version: Id::new(1u64),
            options: vec![
                CommandOption {
                    name: "channel".to_string(),
                    kind: CommandOptionType::SubCommand,
                    description: translator.translate("cmd_desc_set_channel", &language, None),
                    channel_types: None,
                    options: Some(vec![CommandOption {
                        name: "channel".to_string(),
                        kind: CommandOptionType::Channel,
                        description: "A channel of your choice".to_string(),
                        channel_types: Some(vec![
                            ChannelType::GuildText,
                            ChannelType::GuildAnnouncement,
                        ]),
                        required: Some(true),
                        autocomplete: None,
                        description_localizations: None,
                        name_localizations: None,
                        max_length: None,
                        min_length: None,
                        max_value: None,
                        min_value: None,
                        choices: None,
                        options: None,
                    }]),
                    required: None,
                    autocomplete: None,
                    description_localizations: None,
                    name_localizations: None,
                    max_length: None,
                    min_length: None,
                    max_value: None,
                    min_value: None,
                    choices: None,
                },
                CommandOption {
                    name: "thread".to_string(),
                    kind: CommandOptionType::SubCommand,
                    description: translator.translate("cmd_desc_set_channel", &language, None),
                    channel_types: None,
                    autocomplete: Some(false),
                    options: Some(vec![CommandOption {
                        name: "thread".to_string(),
                        kind: CommandOptionType::Channel,
                        description: "A public active thread of your choice".to_string(),
                        required: Some(true),
                        channel_types: Some(vec![ChannelType::PublicThread]),
                        autocomplete: None,
                        description_localizations: None,
                        name_localizations: None,
                        max_length: None,
                        min_length: None,
                        max_value: None,
                        min_value: None,
                        choices: None,
                        options: None,
                    }]),
                    required: None,
                    description_localizations: None,
                    name_localizations: None,
                    max_length: None,
                    min_length: None,
                    max_value: None,
                    min_value: None,
                    choices: None,
                },
                CommandOption {
                    name: "role".to_string(),
                    kind: CommandOptionType::SubCommand,
                    description: translator.translate("cmd_desc_set_role", &language, None),
                    channel_types: None,
                    options: Some(vec![CommandOption {
                        name: "role".to_string(),
                        kind: CommandOptionType::Role,
                        description: "A role of your choice".to_string(),
                        required: Some(true),
                        channel_types: None,
                        autocomplete: None,
                        description_localizations: None,
                        name_localizations: None,
                        max_length: None,
                        min_length: None,
                        max_value: None,
                        min_value: None,
                        choices: None,
                        options: None,
                    }]),
                    required: None,
                    autocomplete: None,
                    description_localizations: None,
                    name_localizations: None,
                    max_length: None,
                    min_length: None,
                    max_value: None,
                    min_value: None,
                    choices: None,
                },
                CommandOption {
                    name: "language".to_string(),
                    kind: CommandOptionType::SubCommand,
                    description: translator.translate("cmd_desc_set_language", &language, None),
                    channel_types: None,
                    options: Some(vec![CommandOption {
                        name: "language".to_string(),
                        kind: CommandOptionType::String,
                        description: "The language".to_string(),
                        required: Some(true),
                        autocomplete: Some(true),
                        channel_types: None,
                        description_localizations: None,
                        name_localizations: None,
                        max_length: None,
                        min_length: None,
                        max_value: None,
                        min_value: None,
                        choices: None,
                        options: None,
                    }]),
                    required: None,
                    autocomplete: None,
                    description_localizations: None,
                    name_localizations: None,
                    max_length: None,
                    min_length: None,
                    max_value: None,
                    min_value: None,
                    choices: None,
                },
                CommandOption {
                    name: "currency".to_string(),
                    kind: CommandOptionType::SubCommand,
                    description: translator.translate("cmd_desc_set_currency", &language, None),
                    channel_types: None,
                    options: Some(vec![CommandOption {
                        name: "currency".to_string(),
                        kind: CommandOptionType::String,
                        description: "The currency".to_string(),
                        required: Some(true),
                        autocomplete: Some(true),
                        channel_types: None,
                        description_localizations: None,
                        name_localizations: None,
                        max_length: None,
                        min_length: None,
                        max_value: None,
                        min_value: None,
                        choices: None,
                        options: None,
                    }]),
                    required: None,
                    autocomplete: None,
                    description_localizations: None,
                    name_localizations: None,
                    max_length: None,
                    min_length: None,
                    max_value: None,
                    min_value: None,
                    choices: None,
                },
            ],
            description_localizations: None,
            name_localizations: None,
            nsfw: None,
            guild_id: None,
            id: None,
            application_id: None,
        },
        Command {
            name: "test".to_string(),
            description: translator.translate("cmd_desc_test", &language, None),
            default_member_permissions: Some(Permissions::MANAGE_GUILD),
            dm_permission: Some(false),
            kind: CommandType::ChatInput,
            version: Id::new(1u64),
            description_localizations: None,
            name_localizations: None,
            nsfw: None,
            options: Vec::new(),
            guild_id: None,
            id: None,
            application_id: None,
        },
        Command {
            name: "debug".to_string(),
            description: translator.translate("cmd_desc_debug", &language, None),
            default_member_permissions: Some(Permissions::MANAGE_GUILD),
            dm_permission: Some(false),
            kind: CommandType::ChatInput,
            version: Id::new(1u64),
            description_localizations: None,
            name_localizations: None,
            nsfw: None,
            options: Vec::new(),
            guild_id: None,
            id: None,
            application_id: None,
        },
    ])
}
