version: "3.9"

x-shared-envs: &sharedEnvs
  REDISHOST: redis
  REDISPORT: "6379"
  EFG_API_INTERNAL_BASEURL: http://api:3000/api
  DISCORD_API_BASEURL: https://discord.com/api/v10
  DISCORD_REDIRECT_URL: http://localhost:3010/api/auth/discord-callback
  ENV: Development

x-shared-bot-envs: &sharedBotEnvs
  <<: *sharedEnvs
  EFG_FRONT_BASEURL: https://staging.epicfreegames.net
  LOGO_URL: https://staging.epicfreegames.net/assets/images/logos/Development.png
  REST_PROXY_URL: http://bot_rest-proxy:3000
  BOT_TOKEN: ${BOT_TOKEN}
  EFG_API_BOT_TOKEN: efg-valid-bot-token

services:
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always
    healthcheck:
      test: mysql -u root -p secret -e SHOW DATABASES
      interval: 3s
      timeout: 15s
      retries: 5

  redis:
    image: redis
    volumes:
      - redis-data:/data
    restart: always

  api:
    depends_on:
      - redis
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    environment:
      <<: *sharedEnvs
      ADMIN_DISCORD_ID: ${ADMIN_DISCORD_ID}
      DISCORD_CLIENT_ID: ${DISCORD_CLIENT_ID}
      DISCORD_CLIENT_SECRET: ${DISCORD_CLIENT_SECRET}
      DATABASE_URL: mysql://root:secret@mysql:3306/efg
      SENDER_URL: http://bot_sender:3000
      JWT_ISS: efg-dev-api
      JWT_AUD: efg-dev-api
      SECRET: efg-api-secret
      DASH_URL: http://localhost:3001
      VALID_BOT_TOKEN: efg-valid-bot-token
      VALID_FRONT_TOKEN: efg-valid-front-token
      VALID_SCRAPER_TOKEN: efg-valid-scraper-token
      VALID_HEALTHCHECK_TOKEN: efg-valid-healthz-token
    restart: always
    volumes:
      - ./api/src:/app/src:r
      - ./api/t10s:/app/t10s:r
    ports:
      - "3010:3000"
    command: sh -c './wait-for.sh mysql:3306 -t 20 -- ./wait-for.sh redis:6379 -t 20 -- yarn prisma db push && yarn dev'

  dash:
    depends_on:
      - api
    build:
      context: ./dash
      dockerfile: Dockerfile.dev
    image: dash/dash
    environment:
      <<: *sharedEnvs
      NEXT_PUBLIC_EFG_API_BASEURL: http://localhost:3010/api
      NEXT_PUBLIC_EFG_API_WS_URL: ws://localhost:3010/api
    volumes:
      - ./dash/src:/app/src:r
    ports:
      - "3001:3000"
    restart: always
    command: sh -c './wait-for.sh api:3000 -t 20 -- yarn dev'

  front:
    build:
      context: ./front
      dockerfile: Dockerfile.dev
    image: front/front
    volumes:
      - ./front/src:/app/src:r
      - ./front/tailwind.config.js:/app/tailwind.config.js:r
    ports:
      - "3000:3000"
    environment:
      EFG_API_FRONT_TOKEN: efg-valid-front-token
      EFG_API_BASEURL: http://api:3000/api
      ENVIRONMENT: Development
    restart: always
    command: sh -c './wait-for.sh api:3000 -t 20 -- yarn dev'

  bot_rest-proxy:
    depends_on:
      - api
    build:
      context: ./bot
      args:
        - SCOPE=rest-proxy
    image: bot_rest-proxy
    environment:
      <<: *sharedBotEnvs
    restart: always
    command: sh -c './wait-for.sh api:3000 -t 20 -- deno run --watch -A ./src/rest-proxy/mod.ts'

  bot_sender:
    depends_on:
      - bot_rest-proxy
    build:
      context: ./bot
      args:
        - SCOPE=sender
    image: bot_sender
    environment:
      <<: *sharedBotEnvs
      WEBHOOK_NAME: Dev-EpicFreeGames
    restart: always
    command: sh -c './wait-for.sh api:3000 -t 20 -- ./wait-for.sh bot_rest-proxy:3000 -t 20 -- deno run --watch -A ./src/sender/mod.ts'

  bot_gateway:
    depends_on:
      - bot_rest-proxy
    build:
      context: ./bot
      args:
        - SCOPE=gateway
    image: bot_gateway
    environment:
      <<: *sharedBotEnvs
      EVENT_HANDLER_URL: http://bot_event-handler:3000
    restart: always
    command: sh -c './wait-for.sh api:3000 -t 20 -- ./wait-for.sh bot_rest-proxy:3000 -t 20 -- deno run --watch -A ./src/gateway/mod.ts'

  bot_event-handler:
    depends_on:
      - bot_gateway
      - bot_rest-proxy
    build:
      context: ./bot
      args:
        - SCOPE=event-handler
    image: bot_event-handler
    environment:
      <<: *sharedBotEnvs
      WEBHOOK_INTEGRATION_NAME: Dev-EpicFreeGames Notifications
    volumes:
      - ./bot/src:/app/src:r
    restart: always
    command: sh -c './wait-for.sh api:3000 -t 20 -- ./wait-for.sh bot_rest-proxy:3000 -t 20 -- deno run --watch -A ./src/event-handler/mod.ts'

volumes:
  redis-data:
  mysql:
