export enum Languages {
  en = "en",
  de = "de",
  fr = "fr",
  es = "es",
  ru = "ru",
  ua = "ua",
  pl = "pl",
  tr = "tr",
  cz = "cz",
  ro = "ro",
  jp = "jp",
  hi = "hi",
  pt = "pt",
  du = "du",
  fa = "fa",
  hu = "hu",
  id = "id",
  ge = "ge",
  vn = "vn",
  ar = "ar",
  it = "it",
  ko = "ko",
}

export const LanguagesWithFlags = {
  en: "🇬🇧 English",
  de: "🇩🇪 Deutsch",
  fr: "🇫🇷 Français",
  es: "🇪🇸 Español",
  ru: "🇷🇺 Pусский",
  ua: "🇺🇦 Український",
  pl: "🇵🇱 Polski",
  tr: "🇹🇷 Türkçe",
  cz: "🇨🇿 čeština",
  ro: "🇷🇴 Română",
  jp: "🇯🇵 日本語",
  hi: "🇮🇳 हिंदी",
  pt: "🇵🇹 Português",
  du: "🇳🇱 Nederlands",
  fa: "🇮🇷 فارسی",
  hu: "🇭🇺 Magyar",
  id: "🇮🇩 Indonesian",
  ge: "🇬🇪 ქართული",
  vn: "🇻🇳 Tiếng Việt",
  ar: "🇸🇦 عربي",
  it: "🇮🇹 Italiano",
  ko: "🇰🇷 한국어",
};
