FROM node:16-alpine AS base

WORKDIR /app

RUN apk update && apk add wget
RUN wget -q -O ./wait-for.sh https://raw.githubusercontent.com/eficode/wait-for/4df3f9262d84cab0039c07bf861045fbb3c20ab7/wait-for && chmod +x ./wait-for.sh

FROM base as builder

COPY ./*.json ./
COPY ./yarn.lock ./
COPY ./*d.ts ./
COPY ./*.js ./

RUN yarn

COPY ./src ./src

ENV NODE_ENV development
ENV NEXT_TELEMETRY_DISABLED 1

CMD yarn dev