name: 'Build images'

on: 
  push:
    branches:   
      - master
    paths: 
      - 'apps/**/*'
      - 'packages/**/*'

jobs:
  build-code:     
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js 16.15.0
      uses: actions/setup-node@v3
      with:
        node-version: '16.15.0'

    - name: Build code
      run: yarn build
  
  determine-images:
    needs: build-code
    name: "Determine images to build"
    runs-on: ubuntu-latest
    outputs:
      some: ${{ steps.builds.outputs.some }}
      i_endpoint: ${{ steps.builds.outputs.i_endpoint }}
      sender: ${{ steps.builds.outputs.sender }}
      web_ui: ${{ steps.builds.outputs.web_ui }}
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Get changed files
      id: getfile
      run: |
        echo "::set-output name=files::$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }}| xargs)"
    - name: Determine builds
      id: builds
      run: |
        setOutput () { 
          echo "::set-output name=$1::true"
          echo "::set-output name=some::true"
          echo "set $1"
        }

        set_i_endpoint () { 
          setOutput i_endpoint
        }
        set_sender () { 
          setOutput sender
        }
        set_web_ui () { 
          setOutput web_ui;
        }

        i_endpoint () {
          if [[ $1 == *"apps/interactions-endpoint"* ]]; then 
            set_integration_tests 
          fi
        }
        sender () {
          if [[ $1 == *"apps/sender"* ]]; then 
            set_sender 
          fi
        }
        web_ui () {
          if [[ $1 == *"apps/web-ui"* ]]; then 
            set_web_ui 
          fi        
        }
    
        for i in ${{ steps.getfile.outputs.files }}
        do
          echo $i
          if [[ $i == *"packages/"* ]]; then
            set_i_endpoint
            set_sender
            set_web_ui
            break
          fi
          i_endpoint $i
          sender $i
          web_ui $i
        done

  build-push-i-endpoint-image:
    needs: determine-images
    name: "Build and push i-endpoint Docker image"
    if: ${{ needs.determine-images.outputs.i_endpoint }}
    uses: ./.github/workflows/build-docker-image.yml
    with:
      scope: i-endpoint
      image-name-tag: veetik/freegames-bot-i-endpoint:latest
    secrets: 
      DH_USERNAME: ${{ secrets.DH_USERNAME }}
      DH_TOKEN: ${{ secrets.DH_TOKEN }}

  build-push-sender-image:
    needs: determine-images
    name: "Build and push sender Docker image"
    if: ${{ needs.determine-images.outputs.sender }}
    uses: ./.github/workflows/build-docker-image.yml
    with:
      scope: sender
      image-name-tag: veetik/freegames-bot-sender:latest
    secrets: 
      DH_USERNAME: ${{ secrets.DH_USERNAME }}
      DH_TOKEN: ${{ secrets.DH_TOKEN }}

  build-push-web-ui-image:
    needs: determine-images
    name: "Build and push web-ui Docker image"
    if: ${{ needs.determine-images.outputs.web_ui }}
    uses: ./.github/workflows/build-docker-image.yml
    with:
      scope: web-ui
      image-name-tag: veetik/freegames-bot-web-ui:latest
    secrets: 
      DH_USERNAME: ${{ secrets.DH_USERNAME }}
      DH_TOKEN: ${{ secrets.DH_TOKEN }}