name: CI/CD

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  bot-api-typecheck:
    name: "Bot & Api: Typecheck"
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous workflows
        uses: styfle/cancel-workflow-action@0.10.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node with Yarn cache
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
          cache-dependency-path: ./yarn.lock

      - name: Install deps
        run: yarn --frozen-lockfile

      - name: Build code
        run: yarn build

  frontends-typecheck:
    name: "Frontends: Typecheck"
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous workflows
        uses: styfle/cancel-workflow-action@0.10.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node with Yarn cache
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
          cache-dependency-path: ./yarn.lock

      - name: Install deps
        run: yarn --frozen-lockfile

      - name: Typecheck
        run: yarn f::typecheck

  bot-api-docker-build-push:
    name: "Bot & Api: build and push Docker images"
    needs: [bot-api-typecheck]
    runs-on: ubuntu-latest
    strategy: 
      matrix: 
        service: 
          - api
          - discord-rest-proxy
          - interactions-endpoint
          - sender
          - under-maintenance
    steps:
      - name: Cancel previous workflows
        uses: styfle/cancel-workflow-action@0.10.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to the container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.REGISTRY }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASS }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.REGISTRY }}/${{ secrets.REGISTRY_USER }}/efg-${{ matrix.service }}
          tags: |
            type=ref,event=branch
            type=sha,format=long

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: ${{ runner.os }}-buildx-

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          build-args: |
            APP=@efg/${{ matrix.service }}
            APP_FOLDER=${{ matrix.service }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

  bot-api-deploy-staging:
    name: "Bot & Api: Deploy to Staging"
    environment: Staging
    runs-on: ubuntu-latest
    needs: [bot-api-docker-build-push]
    steps:
      - name: Cancel previous workflows
        uses: styfle/cancel-workflow-action@0.10.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create folder
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SXX_HOST }}
          username: ${{ secrets.SXX_USERNAME }}
          port: ${{ secrets.SXX_PORT }}
          key: ${{ secrets.SXX_KEY }}
          script: mkdir -p ~/efg-staging

      - name: Update Docker compose file
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.SXX_HOST }}
          username: ${{ secrets.SXX_USERNAME }}
          port: ${{ secrets.SXX_PORT }}
          key: ${{ secrets.SXX_KEY }}
          source: ./docker-compose-staging.yml
          target: /home/${{ secrets.SXX_USERNAME }}/efg-staging
          strip_components: 1

      - name: Recreate containers
        uses: appleboy/ssh-action@v0.1.5
        env:
          REGISTRY: ${{ secrets.REGISTRY }}
          REGISTRY_USER: ${{ secrets.REGISTRY_USER }}
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          DISCORD_CLIENT_SECRET: ${{ secrets.DISCORD_CLIENT_SECRET }}
          SECRET: ${{ secrets.SECRET }}
          VALID_BOT_TOKEN: ${{ secrets.VALID_BOT_TOKEN }}
          VALID_FRONT_TOKEN: ${{ secrets.VALID_FRONT_TOKEN }}
          VALID_SCRAPER_TOKEN: ${{ secrets.VALID_SCRAPER_TOKEN }}
          VERSION: sha-${{ github.sha }}
        with:
          host: ${{ secrets.SXX_HOST }}
          username: ${{ secrets.SXX_USERNAME }}
          port: ${{ secrets.SXX_PORT }}
          key: ${{ secrets.SXX_KEY }}
          script: |
            cd ~/efg-staging \
            && REGISTRY=${{ env.REGISTRY }} \
              REGISTRY_USER=${{ env.REGISTRY_USER }} \
              DISCORD_BOT_TOKEN=${{ env.DISCORD_BOT_TOKEN }} \
              DISCORD_CLIENT_SECRET=${{ env.DISCORD_CLIENT_SECRET }} \
              SECRET=${{ env.SECRET }} \
              VALID_BOT_TOKEN=${{ env.VALID_BOT_TOKEN }} \
              VALID_FRONT_TOKEN=${{ env.VALID_FRONT_TOKEN }} \
              VALID_SCRAPER_TOKEN=${{ env.VALID_SCRAPER_TOKEN }} \
              VERSION=${{ env.VERSION }} \
                docker compose -f docker-compose-staging.yml -p efg-staging up -d --force-recreate

  internal-dash-deploy-staging:
    name: "Internal dash: Deploy to Staging"
    environment: Staging
    runs-on: ubuntu-latest
    needs: [frontends-typecheck]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_DASH }}
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project to Vercel
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_DASH }}
        run: |
          vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }} \
          -e NEXT_PUBLIC_EFG_API_BASEURL=${{ secrets.NEXT_PUBLIC_EFG_API_BASEURL }} \
          -e NEXT_PUBLIC_EFG_API_WS_URL=${{ secrets.NEXT_PUBLIC_EFG_API_WS_URL }} \
          -b NEXT_PUBLIC_EFG_API_BASEURL=${{ secrets.NEXT_PUBLIC_EFG_API_BASEURL }} \
          -b NEXT_PUBLIC_EFG_API_WS_URL=${{ secrets.NEXT_PUBLIC_EFG_API_WS_URL }}

  website-deploy-staging:
    name: "Website: Deploy to Staging"
    environment: Staging
    runs-on: ubuntu-latest
    needs: [frontends-typecheck]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_FRONT }}
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project to Vercel
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_FRONT }}
        run: | 
          vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }} \
            -b EFG_API_BASEURL=${{ secrets.NEXT_PUBLIC_EFG_API_BASEURL }} \
            -b EFG_API_FRONT_TOKEN=${{ secrets.VALID_FRONT_TOKEN }} \
            -b ENV=Staging

  bot-api-deploy-prod:
    name: "Bot & Api: Deploy to Production"
    environment: Production
    runs-on: ubuntu-latest
    needs: [bot-api-deploy-staging]
    steps:
      - name: Cancel previous workflows
        uses: styfle/cancel-workflow-action@0.10.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create folder
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SXX_HOST }}
          username: ${{ secrets.SXX_USERNAME }}
          port: ${{ secrets.SXX_PORT }}
          key: ${{ secrets.SXX_KEY }}
          script: mkdir -p ~/efg-prod

      - name: Update Docker compose file
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.SXX_HOST }}
          username: ${{ secrets.SXX_USERNAME }}
          port: ${{ secrets.SXX_PORT }}
          key: ${{ secrets.SXX_KEY }}
          source: ./docker-compose-prod.yml
          target: /home/${{ secrets.SXX_USERNAME }}/efg-prod
          strip_components: 1

      - name: Recreate containers
        uses: appleboy/ssh-action@v0.1.5
        env:
          REGISTRY: ${{ secrets.REGISTRY }}
          REGISTRY_USER: ${{ secrets.REGISTRY_USER }}
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          DISCORD_CLIENT_SECRET: ${{ secrets.DISCORD_CLIENT_SECRET }}
          SECRET: ${{ secrets.SECRET }}
          VALID_BOT_TOKEN: ${{ secrets.VALID_BOT_TOKEN }}
          VALID_FRONT_TOKEN: ${{ secrets.VALID_FRONT_TOKEN }}
          VALID_SCRAPER_TOKEN: ${{ secrets.VALID_SCRAPER_TOKEN }}
          VERSION: sha-${{ github.sha }}
        with:
          host: ${{ secrets.SXX_HOST }}
          username: ${{ secrets.SXX_USERNAME }}
          port: ${{ secrets.SXX_PORT }}
          key: ${{ secrets.SXX_KEY }}
          script: |
            cd ~/efg-prod \
            && REGISTRY=${{ env.REGISTRY }} \
              REGISTRY_USER=${{ env.REGISTRY_USER }} \
              DISCORD_BOT_TOKEN=${{ env.DISCORD_BOT_TOKEN }} \
              DISCORD_CLIENT_SECRET=${{ env.DISCORD_CLIENT_SECRET }} \
              SECRET=${{ env.SECRET }} \
              VALID_BOT_TOKEN=${{ env.VALID_BOT_TOKEN }} \
              VALID_FRONT_TOKEN=${{ env.VALID_FRONT_TOKEN }} \
              VALID_SCRAPER_TOKEN=${{ env.VALID_SCRAPER_TOKEN }} \
              VERSION=${{ env.VERSION }} \
              DEBUG=1 \
                docker compose -f docker-compose-prod.yml -p efg-prod up -d --force-recreate

  internal-dash-deploy-prod:
    name: "Internal dash: Deploy to Production"
    environment: Production
    runs-on: ubuntu-latest
    needs: [internal-dash-deploy-staging]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_DASH }}
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project to Vercel
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_DASH }}
        run: |
          vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }} \
          -e NEXT_PUBLIC_EFG_API_BASEURL=${{ secrets.NEXT_PUBLIC_EFG_API_BASEURL }} \
          -e NEXT_PUBLIC_EFG_API_WS_URL=${{ secrets.NEXT_PUBLIC_EFG_API_WS_URL }} \
          -b NEXT_PUBLIC_EFG_API_BASEURL=${{ secrets.NEXT_PUBLIC_EFG_API_BASEURL }} \
          -b NEXT_PUBLIC_EFG_API_WS_URL=${{ secrets.NEXT_PUBLIC_EFG_API_WS_URL }}

  website-deploy-prod:
    name: "Website: Deploy to Production"
    environment: Production
    runs-on: ubuntu-latest
    needs: [website-deploy-staging]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_FRONT }}
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project to Vercel
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_FRONT }}
        run: | 
          vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }} \
            -b EFG_API_BASEURL=${{ secrets.EFG_API_BASEURL }} \
            -b EFG_API_FRONT_TOKEN=${{ secrets.VALID_FRONT_TOKEN }} \
            -b ENV=Production