name: "Release workflow"

on:
  push:
    branches:
      - rust
  workflow_dispatch:

jobs:
  deploy-staging:
    environment: "Rust-staging"
    name: "Deploy to Staging"
    runs-on: ubuntu-latest
    steps:
      - name: "Cancel previous workflows"
        uses: styfle/cancel-workflow-action@0.10.0
        with:
          access_token: ${{ github.token }}

      - name: "Checkout code"
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3

      - name: "Setup railway"
        run: "npm i -g @railway/cli"

      - name: "Deploy"
        run: cd backend && railway up
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}